# Generated by Django 4.1.3 on 2022-11-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="project",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.gallery"
            ),
        ),
    ]
